/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bridge.web;

import bridge.ejb.CollegeInfoBean;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import bridge.ejb.UserFacade;
import bridge.entity.College;
import bridge.entity.Sharing;
import bridge.entity.User;
import java.util.List;
import javax.faces.bean.SessionScoped;
import javax.inject.Named;
import bridge.jsf.SharingController;
import javax.faces.context.FacesContext;

@Named
@SessionScoped
@Stateless
public class Search implements Serializable {

    protected int item;
    protected String keyword;
    protected List<Sharing> results1;
    protected List<User> results3;
    protected List<College> results2;

    @EJB
    private SharingController sharingController;
    @EJB
    private UserFacade userFacade;
    @EJB
    private CollegeSearch collegeSearch;
//    @EJB
//    private CollegeController collegeController;

    public List<Sharing> getResults1() {
        return results1;
    }

    public void setResults1(List<Sharing> results1) {
        this.results1 = results1;
    }

    public List<User> getResults3() {
        return results3;
    }

    public void setResults3(List<User> results3) {
        this.results3 = results3;
    }

    public List<College> getResults2() {
        return results2;
    }

    public void setResults2(List<College> results2) {
        this.results2 = results2;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public int getItem() {
        return item;
    }

    public void setItem(int i) {
        this.item = i;
    }
    //Generated by Map
    private static Map<String, Object> itemValue;

    static {
        itemValue = new LinkedHashMap<String, Object>();
        itemValue.put("文章", "1"); //label, value
        itemValue.put("学校", "2");
        itemValue.put("用户", "3");
    }

    public Map<String, Object> getItemValue() {
        return itemValue;
    }

    public String searchBy() {

        if (this.item == 1) {
            return sharingController.getItemsBySharingSearch_user(keyword);

        }
        if (this.item == 3) {
            setResults3(userFacade.searchByUser(keyword));
            return "/User/List.xhtml";
        }
        if (this.item == 2) {
            FacesContext.getCurrentInstance().getPartialViewContext().setRenderAll(true);
            return collegeSearch.scearch_process(keyword);

        }
        return "/welcomePrimefaces.xhtml";
    }

}
